name: moodie_v2
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^2.26.0
  firebase_auth: ^4.17.7
  cloud_firestore: ^4.15.5
  gif_view: ^1.0.2
  http: ^1.3.0
  flutter_dotenv: ^5.2.1
  uuid: ^4.3.3
  intl: ^0.18.1
  flutter_svg: ^2.0.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/img1.png
    - assets/images/img2.png
    - assets/images/img3.png
    - assets/images/img4.png
    - assets/images/personal-growth.svg
    - assets/images/growth2.svg
    - assets/icons/icon-google.png
    - assets/icons/icon-github.png
    - assets/icons/icon-apple.png
    - assets/icons/arrow-left.svg
    - assets/icons/cloud-rain-light.svg
    - assets/icons/cloud-sun-light.svg
    - assets/icons/head-circuit-light.svg
    - assets/icons/leaf-light.svg
    - assets/icons/Vector.svg
    - assets/icons/fire-light.svg
    - assets/icons/chatbubble.svg
    - assets/icons/plus.svg
    - assets/icons/close-sidebar.svg
    - assets/icons/Trash.svg
    - assets/icons/arrow-left.svg
    - assets/images/robot.svg
    - assets/images/meditation.svg
    - assets/images/writing.svg
    - assets/images/prompt.svg
    - assets/images/mood.svg
    - assets/images/serene.svg
    - assets/images/growing.svg
    - assets/images/relaxing-at-home.svg
    - assets/images/positive-thinking.svg
    - assets/images/breathing.svg
    - assets/images/happy-earth.svg
    - assets/images/self-love.svg
    - assets/images/nature-benefits.svg
    - assets/images/Meditation-pana.svg
    - assets/images/Breathing exercise-cuate.svg
    - assets/gifs/bad.gif
    - assets/gifs/good.gif
    - assets/gifs/great.gif
    - assets/gifs/neutral-face.gif
    - assets/gifs/pouting-face.gif
    - assets/fonts/General Sans/GeneralSans-Bold.otf
    - assets/fonts/Playpen/PlaypenSans-Bold.ttf
    - assets/fonts/quicksand/Quicksand_Bold.otf
    # Nav bar SVG icons
    - assets/icons/nav-icons/house.svg
    - assets/icons/nav-icons/house-fill.svg
    - assets/icons/nav-icons/heartbeat.svg
    - assets/icons/nav-icons/heartbeat-fill.svg
    - assets/icons/nav-icons/smiley.svg
    - assets/icons/nav-icons/smiley-fill.svg
    - assets/icons/nav-icons/user-circle.svg
    - assets/icons/nav-icons/user-circle-fill.svg
    - assets/emojis/mood-scale/great.svg
    - assets/emojis/mood-scale/good.svg
    - assets/emojis/mood-scale/so-so.svg
    - assets/emojis/mood-scale/bad.svg
    - assets/emojis/mood-scale/very-bad.svg
    - assets/emojis/annoyance/Confounded face.svg
    - assets/emojis/annoyance/Pensive face.svg
    - assets/emojis/annoyance/Pouting face.svg
    - assets/emojis/annoyance/Tired face.svg
    - assets/emojis/annoyance/Unamused face.svg
    - assets/emojis/energy/Beaming face with smiling eyes.svg
    - assets/emojis/energy/Grinning face with big eyes.svg
    - assets/emojis/energy/Nerd face.svg
    - assets/emojis/energy/Sleepy face.svg
    - assets/emojis/energy/Star-struck.svg
    - assets/emojis/others/Low.svg
    - assets/emojis/others/Numb.svg
    - assets/emojis/others/loved.svg
    - assets/emojis/others/stressed.svg
    - assets/emojis/positive/Content.svg
    - assets/emojis/positive/Face exhaling.svg
    - assets/emojis/positive/Grinning face with smiling eyes.svg
    - assets/emojis/positive/Smiling face with sunglasses.svg
    - assets/emojis/positive/Winking face.svg
    - assets/emojis/stressed/Anxious face with sweat.svg
    - assets/emojis/stressed/Face in clouds.svg
    - assets/emojis/stressed/Knocked-out face.svg
    - assets/emojis/stressed/Sad but relieved face.svg
    - assets/emojis/vibes/1F602_Tears_of_Joy_Smileys_Still 2.svg
    - assets/emojis/vibes/Face with rolling eyes.svg
    - assets/emojis/vibes/Partying face.svg
    - assets/emojis/vibes/Thinking face.svg
    - assets/emojis/vibes/Winking face with tongue.svg
    - assets/emojis/positive/263A FE0F_SmilingFace_1024px_01_01 1.svg
    - assets/emojis/positive/263A FE0F_SmilingFace_1024px_01_01 1.png
    - assets/emojis/positive/1F604_GrinningFaceWithSmilingEyes_1024px_01_04 1.svg
  fonts:
    - family: General Sans
      fonts:
        - asset: assets/fonts/General Sans/GeneralSans-Bold.otf
        - asset: assets/fonts/General Sans/GeneralSans-BoldItalic.otf
        - asset: assets/fonts/General Sans/GeneralSans-Extralight.otf
        - asset: assets/fonts/General Sans/GeneralSans-ExtralightItalic.otf
        - asset: assets/fonts/General Sans/GeneralSans-Italic.otf
        - asset: assets/fonts/General Sans/GeneralSans-Light.otf
        - asset: assets/fonts/General Sans/GeneralSans-LightItalic.otf
        - asset: assets/fonts/General Sans/GeneralSans-Medium.otf
        - asset: assets/fonts/General Sans/GeneralSans-MediumItalic.otf
        - asset: assets/fonts/General Sans/GeneralSans-Regular.otf
        - asset: assets/fonts/General Sans/GeneralSans-Semibold.otf
        - asset: assets/fonts/General Sans/GeneralSans-SemiboldItalic.otf
    - family: Playpen
      fonts:
        - asset: assets/fonts/Playpen/PlaypenSans-Bold.ttf
        - asset: assets/fonts/Playpen/PlaypenSans-Light.ttf
        - asset: assets/fonts/Playpen/PlaypenSans-Medium.ttf
        - asset: assets/fonts/Playpen/PlaypenSans-Regular.ttf
        - asset: assets/fonts/Playpen/PlaypenSans-SemiBold.ttf
    - family: quicksand
      fonts:
        - asset: assets/fonts/quicksand/Quicksand_Light.otf
          weight: 300
        - asset: assets/fonts/quicksand/Quicksand_Light_Oblique.otf
          weight: 300
          style: italic
        - asset: assets/fonts/quicksand/Quicksand_Book.otf
          weight: 400
        - asset: assets/fonts/quicksand/Quicksand_Book_Oblique.otf
          weight: 400
          style: italic
        - asset: assets/fonts/quicksand/Quicksand_Bold.otf
          weight: 700
        - asset: assets/fonts/quicksand/Quicksand_Bold_Oblique.otf
          weight: 700
          style: italic
