name: moodie_v2
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^2.26.0
  firebase_auth: ^4.17.7
  cloud_firestore: ^4.15.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_svg: ^2.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/img1.png
    - assets/images/img2.png
    - assets/images/img3.png
    - assets/images/img4.png
    - assets/icons/icon-google.png
    - assets/icons/icon-github.png
    - assets/icons/icon-apple.png
    - assets/icons/cloud-rain-light.svg
    - assets/icons/cloud-sun-light.svg
    - assets/icons/head-circuit-light.svg
    - assets/icons/leaf-light.svg
    - assets/icons/Vector.svg
    - assets/icons/fire-light.svg
