// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCeiqpgsVDbEYn3e9cC3Ec6u5A7zPscWqk',
    appId: '1:942104383253:web:50fc8aef927a6dcb0ba31c',
    messagingSenderId: '942104383253',
    projectId: 'moodie-v2',
    authDomain: 'moodie-v2.firebaseapp.com',
    storageBucket: 'moodie-v2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcIukFX9q-jCNJS-HNAmOuMy5J2ZYxSbs',
    appId: '1:942104383253:android:0792c355403193f70ba31c',
    messagingSenderId: '942104383253',
    projectId: 'moodie-v2',
    storageBucket: 'moodie-v2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXDcvSGiir0rWQLgjAYstEOPxvh5GLaIY',
    appId: '1:942104383253:ios:9fc82420603f55ff0ba31c',
    messagingSenderId: '942104383253',
    projectId: 'moodie-v2',
    storageBucket: 'moodie-v2.firebasestorage.app',
    iosBundleId: 'com.example.moodieV2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXDcvSGiir0rWQLgjAYstEOPxvh5GLaIY',
    appId: '1:942104383253:ios:9fc82420603f55ff0ba31c',
    messagingSenderId: '942104383253',
    projectId: 'moodie-v2',
    storageBucket: 'moodie-v2.firebasestorage.app',
    iosBundleId: 'com.example.moodieV2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCeiqpgsVDbEYn3e9cC3Ec6u5A7zPscWqk',
    appId: '1:942104383253:web:b9029402044c88ee0ba31c',
    messagingSenderId: '942104383253',
    projectId: 'moodie-v2',
    authDomain: 'moodie-v2.firebaseapp.com',
    storageBucket: 'moodie-v2.firebasestorage.app',
  );
}
